FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY scripts ./scripts

ENTRYPOINT ["python"]
CMD ["/app/scripts/import_nyc_taxi.py"]
